{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2c10f272-f39c-4c5c-bba8-cb5ec97a9d84",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "st.set_page_config(page_title=\"Laser Cut Waste Calculator\", layout=\"wide\")\n",
    "\n",
    "st.title(\"🔧 Laser Cutting Waste & Cost Calculator\")\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "Upload a **CSV or Excel file** containing laser cutting data.\n",
    "The app will calculate:\n",
    "- Material waste\n",
    "- Waste percentage\n",
    "- Money loss in EUR\n",
    "- Daily waste graph\n",
    "\"\"\")\n",
    "\n",
    "# -----------------------------\n",
    "# File Upload\n",
    "# -----------------------------\n",
    "uploaded_file = st.file_uploader(\n",
    "    \"📂 Drag & drop your CSV or Excel file here\",\n",
    "    type=[\"csv\", \"xlsx\"]\n",
    ")\n",
    "\n",
    "if uploaded_file is not None:\n",
    "\n",
    "    # Load file\n",
    "    if uploaded_file.name.endswith(\".csv\"):\n",
    "        df = pd.read_csv(uploaded_file)\n",
    "    else:\n",
    "        df = pd.read_excel(uploaded_file)\n",
    "\n",
    "    st.subheader(\"📄 Raw Input Data\")\n",
    "    st.dataframe(df)\n",
    "\n",
    "    # -----------------------------\n",
    "    # Calculations\n",
    "    # -----------------------------\n",
    "    df[\"total_area\"] = df[\"width\"] * df[\"length\"]\n",
    "    df[\"waste_area\"] = df[\"total_area\"] - df[\"used_area\"]\n",
    "    df[\"waste_percent\"] = (df[\"waste_area\"] / df[\"total_area\"]) * 100\n",
    "    df[\"waste_cost_eur\"] = (df[\"waste_area\"] / df[\"total_area\"]) * df[\"price_eur\"]\n",
    "\n",
    "    # -----------------------------\n",
    "    # KPIs\n",
    "    # -----------------------------\n",
    "    total_area = df[\"total_area\"].sum()\n",
    "    total_waste = df[\"waste_area\"].sum()\n",
    "    total_cost = df[\"waste_cost_eur\"].sum()\n",
    "    total_waste_percent = (total_waste / total_area) * 100\n",
    "\n",
    "    st.subheader(\"📊 Summary\")\n",
    "\n",
    "    col1, col2, col3 = st.columns(3)\n",
    "    col1.metric(\"Total Waste (%)\", f\"{total_waste_percent:.2f}%\")\n",
    "    col2.metric(\"Total Waste Area\", f\"{total_waste:.2f}\")\n",
    "    col3.metric(\"Money Lost (€)\", f\"{total_cost:.2f}\")\n",
    "\n",
    "    # -----------------------------\n",
    "    # Detailed Table\n",
    "    # -----------------------------\n",
    "    st.subheader(\"📋 Detailed Calculations\")\n",
    "    st.dataframe(df)\n",
    "\n",
    "    # -----------------------------\n",
    "    # Daily Waste Graph\n",
    "    # -----------------------------\n",
    "    st.subheader(\"📈 Daily Waste Cost\")\n",
    "\n",
    "    df[\"date\"] = pd.to_datetime(df[\"date\"])\n",
    "    daily_waste = df.groupby(\"date\")[\"waste_cost_eur\"].sum()\n",
    "\n",
    "    fig, ax = plt.subplots()\n",
    "    ax.plot(daily_waste.index, daily_waste.values)\n",
    "    ax.set_xlabel(\"Date\")\n",
    "    ax.set_ylabel(\"Waste Cost (EUR)\")\n",
    "    ax.set_title(\"Daily Laser Cutting Waste Cost\")\n",
    "    plt.xticks(rotation=45)\n",
    "    plt.tight_layout()\n",
    "\n",
    "    st.pyplot(fig)\n",
    "\n",
    "    # -----------------------------\n",
    "    # Download Results\n",
    "    # -----------------------------\n",
    "    st.subheader(\"⬇️ Download Results\")\n",
    "\n",
    "    csv = df.to_csv(index=False).encode(\"utf-8\")\n",
    "    st.download_button(\n",
    "        label=\"Download calculated data as CSV\",\n",
    "        data=csv,\n",
    "        file_name=\"laser_cut_waste_results.csv\",\n",
    "        mime=\"text/csv\"\n",
    "    )\n",
    "\n",
    "else:\n",
    "    st.info(\"👆 Please upload a CSV or Excel file to get started.\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
